default:
  production: TRUE
  verbose: FALSE
  name: "source"
  title:
    en: "Compositional Data Analysis"
    fr: "Analyse de données de composition"
  description:
    en: |
      Provenance studies rely on the identification of probable sources,
      such that the variability between two sources is greater than the internal
      variability of a single source (the so-called, *provenance postulate*).
      This assumes that a unique signature can be identified for each source on
      the basis of several criteria.

      This application is designed for chemical fingerprinting and source
      tracking of ancient materials. It provides provides tools for the
      exploration, visualization and analysis of compositional data in the
      framework of Aitchison (1986). If you are unfamiliar with the concepts and
      challenges of compositional data analysis, the following publications are a
      good place to start:

      - Egozcue, J. J., Gozzi, C., Buccianti, A. & Pawlowsky-Glahn, V. (2024).
        Exploring Geochemical Data Using Compositional Techniques: A Practical
        Guide. *Journal of Geochemical Exploration*, 258: 107385.
        DOI: [10.1016/j.gexplo.2024.107385](https://doi.org/10.1016/j.gexplo.2024.107385).
      - Greenacre, M. & Wood, J. R. (2024). A Comprehensive Workflow for
        Compositional Data Analysis in Archaeometry, with Code in R.
        *Archaeological and Anthropological Science*, 16: 171.
        DOI: [10.1007/s12520-024-02070-w](https://doi.org/10.1007/s12520-024-02070-w)
      - Grunsky, E., Greenacre, M. & Kjarsgaard, B. (2024). GeoCoDA: Recognizing
        and Validating Structural Processes in Geochemical Data. A Workflow on
        Compositional Data Analysis in Lithogeochemistry. *Applied Computing and
        Geosciences*, 22: 100149.
        DOI: [10.1016/j.acags.2023.100149](https://doi.org/10.1016/j.acags.2023.100149).
    fr: |
      Les études de provenance reposent sur l'identification de sources probables,
      de sorte que la variabilité entre deux sources est supérieure à la
      variabilité interne d'une unique source (*postulat de la provenance*).
      Cela suppose qu'une signature unique puisse être identifiée pour chaque
      source sur la base de plusieurs critères.

      Cette application est conçue pour la détermination de signatures chimiques
      et des source de matériaux anciens. Elle fournit des outils pour
      l'exploration, la visualisation et l'analyse des données de composition
      telles que définies par Aitchison (1986). Si vous n'êtes pas familier avec
      les concepts et enjeux de l'analyse des données de composition, les
      publications suivantes sont un bon point de départ :

      - Egozcue, J. J., Gozzi, C., Buccianti, A. & Pawlowsky-Glahn, V. (2024).
        Exploring Geochemical Data Using Compositional Techniques: A Practical
        Guide. *Journal of Geochemical Exploration*, 258: 107385.
        DOI: [10.1016/j.gexplo.2024.107385](https://doi.org/10.1016/j.gexplo.2024.107385).
      - Greenacre, M. & Wood, J. R. (2024). A Comprehensive Workflow for
        Compositional Data Analysis in Archaeometry, with Code in R.
        *Archaeological and Anthropological Science*, 16: 171.
        DOI: [10.1007/s12520-024-02070-w](https://doi.org/10.1007/s12520-024-02070-w)
      - Grunsky, E., Greenacre, M. & Kjarsgaard, B. (2024). GeoCoDA: Recognizing
        and Validating Structural Processes in Geochemical Data. A Workflow on
        Compositional Data Analysis in Lithogeochemistry. *Applied Computing and
        Geosciences*, 22: 100149.
        DOI: [10.1016/j.acags.2023.100149](https://doi.org/10.1016/j.acags.2023.100149).

test:
  production: FALSE
  verbose: TRUE
