default:
  production: TRUE
  verbose: FALSE
  name: "source"
  title: "Compositional Data Analysis"
  description: |
    Provenance studies rely on the identification of probable sources,
    such that the variability between two sources is greater than the internal
    variability of a single source (the so-called, *provenance postulate*).
    This assumes that a unique signature can be identified for each source on
    the basis of several criteria.

    This application is designed for chemical fingerprinting and source
    tracking of ancient materials. It provides provides tools for the
    exploration, visualization and analysis of compositional data in the
    framework of Aitchison (1986).

test:
  production: FALSE
  verbose: TRUE
