default:
  production: TRUE
  verbose: FALSE
  name: "pca"
  title: "Principal Components Analysis"
  description: |
    This app allows to computes a principal components analysis based on the
    singular value decomposition.

test:
  production: FALSE
  verbose: TRUE
