default:
  production: TRUE
  verbose: FALSE
  name: "CA"
  title: "Correspondence Analysis"
  description: |
    This app allows to computes a correspondence analysis based on the
    singular value decomposition.
  workflow: |
    * **Data.** Import your data and perform basic data cleansing and preparation steps.

test:
  production: FALSE
  verbose: TRUE
