default:
  production: TRUE
  verbose: FALSE
  name: "AORISTIC"
  title: "Aoristic Analysis"
  description: |
    This app allows to perform aoristic analysis of time intervals. Aoristic
    analysis can be used to determine the probability of contemporaneity of
    archaeological sites or assemblages. The aoristic analysis distributes the
    probability of an event uniformly over each temporal fraction of the period
    considered. The aoristic sum is then the distribution of the total number
    of events to be assumed within this period.

test:
  production: FALSE
  verbose: TRUE
