default:
  production: TRUE
  verbose: FALSE
  name: "diversity"
  title: "Diversity Measures"
  description: |
    This application allows to compute several diversity measures from a count
    table (absolute frequencies giving the number of individuals for each
    category, i.e. a contingency table).

test:
  production: FALSE
  verbose: TRUE
